# Generated by Django 5.0.14 on 2026-06-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_onboarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image_url',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
