# Generated by Django 5.0.14 on 2026-06-23 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_profile_image_url_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='coord_updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='coord_x',
        ),
        migrations.RemoveField(
            model_name='user',
            name='coord_y',
        ),
    ]
