# Generated by Django 5.0.14 on 2026-06-20 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_key',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
